version: "2.2"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    user: "0"
    container_name: es01
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - esconf01:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    networks:
      - elastic
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es02,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512 -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    user: "0"
    container_name: es02
    volumes:
      - esdata02:/usr/share/elasticsearch/data
      - esconf02:/usr/share/elasticsearch/config
    networks:
      - elastic
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es03
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512 -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    user: "0"
    container_name: es03
    volumes:
      - esdata03:/usr/share/elasticsearch/data
      - esconf03:/usr/share/elasticsearch/config
    networks:
      - elastic
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512 -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  esdata01:
    driver: local
  esconf01:
    driver: local
  esdata02:
    driver: local
  esconf02:
    driver: local
  esdata03:
    driver: local
  esconf03:
    driver: local


networks:
  elastic:
    driver: bridge

